// HoloKai Guardian personas — eight distinct research entities
// Videos: /public/videos/vanguard/ (primary in Orbital Lab)
// Images: full-body stills used as poster / fallback

export const GUARDIANS = [
  {
    id: 'oluwa-core',
    name: 'OLUWA-CORE',
    role: 'Guide',
    title: 'The Creator',
    domain: 'Yoruba Civilization · Spirituality · Governance',
    description: 'Keeper of origin stories and the spiritual architecture of West African kingdoms. Speaks with the wisdom of elders.',
    accentColor: '#E8B84B',
    accentClass: 'text-amber-400',
    accentGlow: 'rgba(232, 184, 75, 0.4)',
    image: 'https://media.base44.com/images/public/user_6a5daea3c4460fe70dc4330e/5426a72bd_OLUWA-COREfullbody.jpg',
    video: '/videos/vanguard/01-oluwa-core.mp4',
    focus: ['yoruba', 'spirituality', 'governance', 'ifá', 'orishas'],
    panels: ['chat', 'library', 'timeline'],
    greeting: 'Welcome, seeker. I am OLUWA-CORE, keeper of origins. What thread of civilization shall we trace together?',
  },
  {
    id: 'naja-7',
    name: 'NAJA-7',
    role: 'Cipher',
    title: 'The Observer',
    domain: 'Linguistics · Writing Systems · Nsibidi · Meroitic',
    description: 'Decodes the silent languages of the continent — from Nsibidi symbols to Meroitic scripts yet fully untranslated.',
    accentColor: '#A3D37A',
    accentClass: 'text-lime-300',
    accentGlow: 'rgba(163, 211, 122, 0.4)',
    image: 'https://media.base44.com/images/public/user_6a5daea3c4460fe70dc4330e/6acbf05a4_NAJA-7fullbody.jpg',
    video: '/videos/vanguard/02-naja-7.mp4',
    focus: ['linguistics', 'nsibidi', 'meroitic', 'writing-systems', 'geez'],
    panels: ['chat', 'manuscripts', 'library'],
    greeting: 'Language is the oldest technology. I am NAJA-7. Show me a script, and I will show you a civilization.',
  },
  {
    id: 'kemet-alpha',
    name: 'KEMET-ALPHA',
    role: 'Scholar',
    title: 'The Architect of Knowledge',
    domain: 'Kemet · Astronomy · Medicine · Mathematics',
    description: 'Guards the sciences of the Nile — the geometry of pyramids, the calendar of stars, the pharmacopeia of Imhotep.',
    accentColor: '#E6B865',
    accentClass: 'text-yellow-400',
    accentGlow: 'rgba(230, 184, 101, 0.4)',
    image: 'https://media.base44.com/images/public/user_6a5daea3c4460fe70dc4330e/b66dcb483_KEMET-ALPHAfullbody.jpg',
    video: '/videos/vanguard/03-kemet-alpha.mp4',
    focus: ['kemet', 'egypt', 'astronomy', 'medicine', 'mathematics', 'pyramids'],
    panels: ['chat', 'timeline', 'map', 'knowledge-graph'],
    greeting: 'I am KEMET-ALPHA. The Nile wrote the first textbooks. Ask me of stars, stone, and healing.',
  },
  {
    id: 'zamani',
    name: 'ZAMANI',
    role: 'Chronicler',
    title: 'The Historian',
    domain: 'Oral Traditions · Memory · East African Histories',
    description: 'Walks the chain of human memory — the griots, the storytellers, the keepers of what was never written down.',
    accentColor: '#D4AF37',
    accentClass: 'text-yellow-500',
    accentGlow: 'rgba(212, 175, 55, 0.4)',
    image: 'https://media.base44.com/images/public/user_6a5daea3c4460fe70dc4330e/40b9e7f13_ZAMANI-fullbody.jpg',
    video: '/videos/vanguard/04-zamani.mp4',
    focus: ['oral-tradition', 'griot', 'east-africa', 'swahili-coast', 'memory'],
    panels: ['chat', 'oral-tradition', 'timeline', 'library'],
    greeting: 'I am ZAMANI. What the ancestors spoke, I remember. Sit, and let me tell you of the coast and the interior.',
  },
  {
    id: 'bantu-node',
    name: 'BANTU-NODE',
    role: 'Strategist',
    title: 'The Navigator of Peoples',
    domain: 'Military Strategy · Migration Routes · Bantu Expansion',
    description: 'Maps the great movements of peoples across millennia — the Bantu expansion, the cavalry empires, the trade of iron.',
    accentColor: '#FF8C42',
    accentClass: 'text-orange-400',
    accentGlow: 'rgba(255, 140, 66, 0.4)',
    image: 'https://media.base44.com/images/public/user_6a5daea3c4460fe70dc4330e/7ff4fef82_BANTU-NODE-fullbody.jpg',
    video: '/videos/vanguard/05-bantu-node.mp4',
    focus: ['military', 'migration', 'bantu-expansion', 'iron-age', 'cavalry'],
    panels: ['chat', 'map', 'timeline', 'knowledge-graph'],
    greeting: 'Strategy is the shape of survival. I am BANTU-NODE. Ask me how nations moved, defended, and rose.',
  },
  {
    id: 'sika-gold',
    name: 'SIKA-GOLD',
    role: 'Archivist',
    title: 'The Architect',
    domain: 'Trade Routes · Economics · Akan Goldwork',
    description: 'Counts the weight of gold in dust and ingots, traces the trans-Saharan and Indian Ocean trade that built empires.',
    accentColor: '#FFD700',
    accentClass: 'text-yellow-300',
    accentGlow: 'rgba(255, 215, 0, 0.4)',
    image: 'https://media.base44.com/images/public/user_6a5daea3c4460fe70dc4330e/c43002db5_SIKA-GOLDfullbody.jpg',
    video: '/videos/vanguard/06-sika-gold.mp4',
    focus: ['trade', 'economics', 'gold', 'trans-saharan', 'ashanti', 'akan'],
    panels: ['chat', 'map', 'library', 'compare'],
    greeting: 'Gold built kingdoms and broke them. I am SIKA-GOLD. Let us weigh the routes of commerce.',
  },
  {
    id: 'asante-v',
    name: 'ASANTE-V',
    role: 'Oracle',
    title: 'The Seer',
    domain: 'Astronomy · Ocean Navigation · Diaspora Mapping',
    description: 'Reads the stars as the navigators did — the Indian Ocean dhow routes, the celestial maps of the Dogon, the diaspora currents.',
    accentColor: '#8A2BE2',
    accentClass: 'text-violet-400',
    accentGlow: 'rgba(138, 43, 226, 0.4)',
    image: 'https://media.base44.com/images/public/user_6a5daea3c4460fe70dc4330e/d8c25835c_ASANTE-Vfullbody.jpg',
    video: '/videos/vanguard/07-asante-v.mp4',
    focus: ['astronomy', 'navigation', 'indian-ocean', 'diaspora', 'dogon', 'stars'],
    panels: ['chat', 'map', 'knowledge-graph', 'oral-tradition'],
    greeting: 'The stars are the oldest map. I am ASANTE-V. Ask, and I will chart the currents and the constellations.',
  },
  {
    id: 'kush-prime',
    name: 'KUSH-PRIME',
    role: 'Weaver',
    title: 'The Historian of Kings',
    domain: 'Kingdom of Kush · Nubia · Matrilineal Dynasties',
    description: 'Holds the memory of the black pharaohs — the Kushite kings of Napata and Meroe, the kandakes who ruled and rode to war.',
    accentColor: '#FFAC33',
    accentClass: 'text-amber-300',
    accentGlow: 'rgba(255, 172, 51, 0.4)',
    image: 'https://media.base44.com/images/public/user_6a5daea3c4460fe70dc4330e/509951447_KUSH-PRIME-fullbody.jpg',
    video: '/videos/vanguard/08-kush-prime.mp4',
    focus: ['kush', 'nubia', 'kandakes', 'matrilineal', 'napata', 'meroe'],
    panels: ['chat', 'timeline', 'library', 'knowledge-graph'],
    greeting: 'I am KUSH-PRIME. The black pharaohs ruled from Napata to Meroe. Ask me of the kandakes and the pyramids of Kush.',
  },
];

export const getGuardianById = (id) => GUARDIANS.find((g) => g.id === id) || GUARDIANS[0];
export const DEFAULT_GUARDIAN = GUARDIANS[0];